export const copy = {
  landingHeadline: "Find Your Perfect Cricket Kit",
  landingSubheadline: "AI-powered recommendations tailored to how you play",
  startExperience: "Start Experience",
  step1Title: "Welcome",
  step1Subtitle: "Enter your details — we'll send a quick OTP to your WhatsApp number.",
  step2Title: "Your profile",
  step2Subtitle: "Help us understand you for the best kit fit.",
  step2GenderTitle: "Who is this kit for?",
  step2GenderSubtitle: "Select the profile that best matches the player.",
  step2MeasurementsTitle: "Measurements",
  step3Title: "Your game",
  step3Subtitle: "Tell us how you play — we'll match gear to your style.",
  cricketKit: "Cricket Kit",
  badmintonKit: "Badminton Kit",
  comingSoonTitle: "Coming Soon",
  comingSoonBody: "Badminton recommendations are on the way. Stay tuned.",
  backToCategories: "Back to categories",
  stepUser: "Your details",
  stepPhysical: "Profile",
  stepPlaying: "Playing style",
  recommendationTitle: "Recommended For You",
  recommendationSubtitle: "Curated for your profile — premium picks ready to explore.",
  categoriesTitle: "Choose Your Sport",
  categoriesSubtitle: "Select a category to begin your personalised fitting experience.",
  viewDetails: "View Details",
  batKnockingGuide: "Bat knocking guide",
  knockingGuideLoading: "Loading knocking guide…",
  knockingGuideError: "Could not load knocking guide. Please try again.",
  knockingGuideWarning:
    "Warning: Never use a brand new bat in a match without full knocking. It can crack on the first hard ball impact.",
  tryAgain: "Try again",
  close: "Close",
  startAgain: "Start Again",
  continue: "Continue",
  verifyOtp: "Verify OTP",
  verifyAndContinue: "Verify & continue",
  sendOtp: "Send OTP",
  resendOtp: "Resend OTP",
  otpSentSuccess: "OTP sent successfully. Enter the code below.",
  verifyMobileFirst: "Verify your mobile number on Your details before opening Profile.",
  mobileVerified: "Mobile verified",
  completeVerification: "Verify your mobile to continue to Profile.",
  fullscreen: "Fullscreen",
  exitFullscreen: "Minimize",
  kitCategoriesTitle: "What do you need?",
  kitCategoriesSubtitle: "Select one or more categories — we will tailor your kit recommendations.",
  kitCategoriesContinue: "Continue to your details",
  kitCategoriesSelectOne: "Select at least one category to continue.",
  kitCategoriesSelected: "selected",
  kitCategoriesSelectAll: "Select all",
  kitCategoriesClear: "Clear",
  kitCategoriesLoading: "Loading categories…",
  kitCategoriesError: "Could not load categories. Please try again.",
  kitProfileSummary: "Kit profile",
  kitTabBat: "Bat",
  kitMatchScore: "Match score",
  kitRecommendationReason: "Why this fits",
  kitMatchedFields: "Matched",
  kitMissingFields: "Gaps",
  batFallbackNoticeTitle: "Closest available option",
  ballTypeTitle: "Ball type",
  ballTypeSubtitle: "Which ball do you play with?",
  ballTypeRequired: "Select a ball type for Kashmir Willow bats.",
  batAiOverviewTitle: "Personalised bat guidance",
  batAiBatSpecAdvice: "Bat profile for your game",
  batAiWillowAdvice: "Willow & grade",
  batAiBeginnerAdvice: "Getting started",
  batAiSkillTips: "Skill development tips",
  batAiBestPickTitle: "Your top bat pick",
  batAiPlayerMatchTitle: "Pro style match",
  batAiSummaryTitle: "Before you buy",
  batAiBrandCompare: "Compare brands",
  batAiBuyingAdvice: "Buying advice",
  batAiKnockingTips: "Knocking & preparation",
  batAiShopkeeperPitch: "Expert recommendation",
};
